# save_data: random-init/run/example

src_vocab: nl-bash/run/example.vocab.src
tgt_vocab: nl-bash/run/example.vocab.tgt

# overwrite: False

data:
  corpus_1:
    path_src: nl-bash/src-train.txt
    path_tgt: nl-bash/tgt-train.txt
  valid:
    path_src: nl-bash/src-val.txt
    path_tgt: nl-bash/tgt-val.txt


# Report
wandb_project: nl2bash

# GPU configuration
world_size: 1
gpu_ranks: [0]

# Where to save checkpoints
save_model: random-init/run/model
save_checkpoint_steps: 100

# Define model
encoder_type: transformer
decoder_type: transformer
word_vec_size: 512
rnn_size: 512
layers: 6
heads: 8
transformer_ff: 2048
batch_size: 64
dropout: 0.1
position_encoding: 'true'

# Initialize parameters
param_init_glorot: true

# define optimizer
optim: adam
accum_count: 8
adam_beta1: 0.9
adam_beta2: 0.998
decay_method: noam
learning_rate: 0.0
max_grad_norm: 0.0


train_steps: 1
valid_steps: 500
warm_up_steps: 160
report_every: 1
