save_data: pretraining/spider/run/example

src_vocab: pretraining/spider/run/nl.vocab.src
tgt_vocab: pretraining/spider/run/code.vocab.tgt

overwrite: False

data:
  corpus_1:
    path_src: pretraining/spider/src-train.txt
    path_tgt: pretraining/spider/tgt-train.txt
  valid:
    path_src: pretraining/spider/src-test.txt
    path_tgt: pretraining/spider/tgt-test.txt

# Record run on wandb
wandb: true
wandb_project: nl2bash

# GPU configuration
world_size: 2
gpu_ranks:
  - 0
  - 1

# Where to save checkpoints
# save_model: pretraining/spider/run/nl-python
save_checkpoint_steps: 100
keep_checkpoint: 3

# Reproducibility
seed: 9001

# Define model
encoder_type: transformer
decoder_type: transformer
word_vec_size: 512
rnn_size: 512
layers: 6
heads: 8
transformer_ff: 2048

# Define hyperparams
batch_size: 2048
batch_type: tokens
normalization: tokens
valid_batch_size: 512
dropout: 0.1
label_smoothing: 0.1
position_encoding: true

# Initialization
param_init: 0.0
param_init_glorot: true
replace_unk: true

# define optimizer
optim: adam
accum_count: 8
adam_beta1: 0.9
adam_beta2: 0.998
decay_method: noam
learning_rate: 2.0
max_grad_norm: 0.0

# Freeze layers
# freeze_encoder: true
# freeze_decoder: true


train_steps: 2500
valid_steps: 100
warm_up_steps: 8000
report_every: 10
